### ISSUE TITLE
Point annotation size

### ISSUE THREAD

**Issue by ds2268** [DigitalSlideArchive/HistomicsUI#106]
You can define "border" size for each annotation (e.g point), but can you also define default size for "point" annotations. This is important when you label cells of interest with points and they become cluttered on lower zoom values (e.g. 10 vs. 20 vs. 40). Is there a way to specify defaults "point" size?

**Comment by manthey** [comment]
Not currently.  It would need to be added in the annotation schema.  The schema does have a circle primitive, but we've never actually used it (and don't currently render it).

From a display standpoint, there are lots of things that could be done: scaling points based on zoom level, clustering at different zoom levels, a single global point size just for controlling the display (which wouldn't require adding radius to the schema).

**Comment by ds2268** [comment]
Is there an easy fix where we can hard code it to be smaller size? We have some problems to labels cells as the annotation if too big and it obscures other cells. Thanks!

**Comment by manthey** [comment]
A quick hack would be to add `radius: <value in pixels>` just above https://github.com/girder/large_image/blob/master/girder_annotation/girder_large_image_annotation/web_client/annotations/style.js#L42.  Remember to rebuild the girder web client making such a change.
