### ISSUE TITLE
Custom new panel

### ISSUE THREAD

**Issue by ds2268** [DigitalSlideArchive/HistomicsUI#111]
We would like to add a new custom panel that will be showing the counters for each particular annotation style (i.e. how many cells of a particular class were already labeled on this particular slide). How can we achieve that? They would need to be separated by annotation documents.

 I guess that we need to extend HistomicsUI/web_client/panels with a new panel?

**Comment by ds2268** [comment]
Alternative would also be to just show in the Draw widget also the ID (number) of the currently added element - so that there would be the name of the annotation element (as it is now) and then counter of the element added element (ID). So that one can track how many instances of that particular annotation have you added in the current annotation document. Maybe this would be even easier to implement for us and achieve the same goal. Can you points us also in this direction, how to achieve that?

**Comment by manthey** [comment]
Adding a panel (or modifying the UI in general) can be done by creating another Girder plugin and adding your code to it.  For instance, a basic Girder plugin can be created using the a cookiecutter template (see https://github.com/girder/cookiecutter-girder-plugin).  There are a number of plugins that add panels (see, for instance, https://github.com/arclamp/annotation-tracker/tree/master/annotation_tracker).

Plugins can also be used to change how any existing element renders, so you could add your additional information to the existing widgets by hooking their render function and changing the behavior.

See also https://girder.readthedocs.io/en/latest/plugin-development.html, specifically https://girder.readthedocs.io/en/latest/plugin-development.html#extending-the-client-side-application.
