### ISSUE TITLE
Install HistomicsUI as girder plugin unsuccessfully

### ISSUE THREAD

**Issue by sunaifei** [DigitalSlideArchive/HistomicsUI#120]
I don’t see the gear icon in ‘Admin console’ - ‘Plugins’ - ‘HistomicsUI’
I install HistomicsUI by following steps：

1.pip install HistomicsUI
2.girder build
    When I execute girder build:
    
![8242d915d9dd49a08ad03c1441d8de9](https://user-images.githubusercontent.com/72735285/151644909-30266490-754c-4641-9c66-355c7ec8cd6b.png)
3. girder serve

**Comment by manthey** [comment]
What version of node are you using?  Can you see if this works with node 12.x?

**Comment by manthey** [comment]
Closing this without further information.
