### ISSUE TITLE
Point annotations - missing

### ISSUE THREAD

**Issue by ds2268** [DigitalSlideArchive/HistomicsUI#125]
I am running a project where pathologists are using point-wise annotations to select particular cells of interest. When clicking on the cells in a fast manner, lots of the cells are not marked and are missed. This is due to HistomicsUI sensitivity to the actual clicking -> it detects that you are trying to move the slide (by the slightest amount) and not to click. Is there some workaround where we can make some "safety margin", that when you are using annotation tools, that it's more sensitive towards putting the annotation there instead of moving the slide around - if the movement detected is really small and annotation tools are selected, put the annotation instead, or both?

Any ideas? This is a real bottleneck in speed, especially when using a stylus pen for making the annotations.

**Comment by ds2268** [comment]
That would be exactly what I need @manthey! Can you please point me in HistomicsUI code, where should I put this exactly? Thanks!

**Comment by manthey** [comment]
Yes, exactly.

You could add it right after this line:
https://github.com/DigitalSlideArchive/HistomicsUI/blob/master/histomicsui/web_client/views/body/ImageView.js#L197

**Comment by ds2268** [comment]
Thanks! Seems to work now - I have exactly no JS experience, so I am doing it a bit blindly :). The clicking seems to be better now but will do a test again with the stylus pen and report. Then you can also consider that as a "standard" feature, or at least to be configurable somewhere if deemed useful in the real world.

**Comment by ds2268** [comment]
@manthey when you are doing point annotations the points (all of them, including previous ones) are rendered again when you add a new one. This makes the labeling process very slow under a high number of points. This can happen when you are labeling manually and come up with thousands of points, but even sooner if you use a semi-automated approach and you add/correct some of them. This makes the process extremely slow.

I noticed that only annotations (i.e. points) under the same annotation file are getting re-rendered. Can I somehow stop re-rendering when adding points under the SAME annotation file and how? Thanks!
