### ISSUE TITLE
Active learning architecture design

### ISSUE THREAD

**Issue by jeffbaumes** [DigitalSlideArchive/HistomicsUI#142]
@naglepuff Could you make the docs world-readable and link them to this issue?

Once you integrate the feedback from today's meeting we can mark this issue as done.

**Comment by naglepuff** [comment]
Text document: https://docs.google.com/document/d/1l7_buWls_TcbAjXzVMVVIsenlUW0sqIKAd6rYfsPHcY/edit?usp=sharing
Diagram: https://drive.google.com/file/d/1N51At73jA3QioEaOpcdwyhsxfIaOEgwn/view?usp=sharing
@cooperlab 

Still do to:
- [ ] update documents with recent feedback
