### ISSUE TITLE
Make "Open in HistomicsUI" a button

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsUI#146]
Currently, this is an entry in the Item Actions menu, but this is less discoverable and requires an extra click than if it were a button.

We could also expose a button in the Hierarchy View.

**Comment by marySalvi** [comment]
As stated above, the button is currently in the Actions menu:
![Screenshot from 2022-06-09 23-17-30](https://user-images.githubusercontent.com/40494088/172987693-534d717c-350c-4ba9-8d88-dca1f3278ce4.png)
Add a button to the Hierarchy View Widget:
![Screenshot from 2022-06-09 23-58-40](https://user-images.githubusercontent.com/40494088/172987889-6807e6a0-2d3e-413a-bf11-86945ddd5897.png)
I believe a good way to achieve this would be to implement js similar to that found in:
https://github.com/DigitalSlideArchive/HistomicsUI/blob/ca1b15db3d2f500d9c004f532b5cec38d1fda85d/histomicsui/web_client/views/itemPage.js#L48-L50

@eagw
