### ISSUE TITLE
Object counter and area

### ISSUE THREAD

**Issue by ds2268** [DigitalSlideArchive/HistomicsUI#174]
It would be good to have some widgets with statistics in them with regards to the number of the elements labeled and possibly an area. I give 2 examples below, that are integrated into the elements widget. We have extended the HistomicsUI with this functionality, but it has stopped working with the latest update (https://github.com/DigitalSlideArchive/HistomicsUI/pull/173). It currently only works on the actual full refresh, which makes sense with the latest update.

It would be good to have such a functionality properly integrated again as a live counter in an efficient manner by the developers, in comparison with our quick and dirty solution :) Maybe as a separate widget? This functionality request came from the field, as the pathologists need to know the area and the number of cells/objects of interest in the annotation. This kind of data needs to be easily accessible and not hidden behind some menus.

<img width="321" alt="image" src="https://user-images.githubusercontent.com/25041003/173313233-4249ba59-05fa-4577-8016-2cd24a30731c.png">

<img width="321" alt="image" src="https://user-images.githubusercontent.com/25041003/173313403-bcdcf08a-5087-4a40-9c4f-49a3199669da.png">

What do you think @manthey ?

**Comment by manthey** [comment]
Areas of individual annotation elements is already available if you hover over an annotation element and have the Labels option checked.  Having the total area and count is a good idea, though.

**Comment by cooperlab** [comment]
It's nice to have this information available. Calculating this with girder client scripts is not trivial.

**Comment by manthey** [comment]
There are a number of ways to aggregate data for counts: by label, by group, by annotation type.  Similarly, we could show total area and/or total perimeter also aggregated in the same manner.  What would be the most useful?  Or should there be options?  Or should we show all combinations?

**Comment by cooperlab** [comment]
I think by group? To me, group represents the notion of "class" best since it is filled by default during annotation. The label field is not populated in many protocols, so elements often have blank label fields. Group, however, is required.

**Comment by ds2268** [comment]
I would also say that the only usable statistics would be in terms of semantic classes, which are the groups. The raw annotation type I don't think is really useful to have in practice (for the actual end-users).

**Comment by manthey** [comment]
As an initial implementation of this, I think I would only show counts when there are at least two annotation elements.  Counts would be separate per group (not by label or annotation type).  An empty group ends up being the "default" group.  I'd keep the summary fairly compact to not use too much screen real estate.

Also, speed in adding annotations is important, so as we add (or delete) an annotation element, we insert (or remove) the appropriate html elements rather than rerendering the panel.  The counts should also update without rerendering the panel.

**Comment by manthey** [comment]
@ds2268 I'll close this issue, as #198 added element counts.  If you think it worth showing the area of each element or of all of the elements, can you make a new issue regarding that.

**Comment by ds2268** [comment]
I have tried the latest versions and don't know if it pulled it correctly:

<img width="307" alt="image" src="https://user-images.githubusercontent.com/25041003/179943871-a12376ed-f8c0-4e66-8113-34f46148de4d.png">

Does this look like my old implementation? I have Docker rmi the old girder and worker images, as well as cloned the HistomicsUI repo and then used the devops scripts to build it. When I connect to the girder container I can see that the HistomicsUI repo is this one and not my old one, with the latest commits, but then the platform seems to show the solution and behavior that I had previously?

**Comment by manthey** [comment]
The style of the counts is definitely not what is in master:
![image](https://user-images.githubusercontent.com/8781639/179978801-6ea8359f-b7ed-4de7-a859-eaa593b3b33c.png)
Is your code overriding the new code?  Are you sure you have the latest version (you can check the version of the HistomicsUI plugin in GET system/plugins).

**Comment by ds2268** [comment]
Problem solved. Browser cache problem. 

Looks to be working fine. For the areas, it would be good to have them for all, but this is specific. In our case, we have some bigger regions in which cells are labeled and it's good to know for the pathologists what is the area (e.g. hot-spot region). It needs to be of sufficient size to be sound. This information is reachable, as you mentioned, but it's hidden and not that useful. I agree that presenting the area at each element would hinder the usefulness in some other cases where you have some segmentation of thousands of objects where displaying the area would not make sense. One option is to have a flag where you can enable or disable displaying the area for each element, but by default just have a total area displayed per group (and only if polygon or rectangle).
