### ISSUE TITLE
Default annotation element name

### ISSUE THREAD

**Issue by manthey** [DigitalSlideArchive/HistomicsUI#195]
Annotation elements are named by their label.  If there is no label specified, the default to their type (polygon, line, rectangle, etc).  This leads to long lists of "polygon", etc.

It would be better to default to the annotation element style, possibly also with the type and a numerical counter.  If we add a counter needs to behave sensibly when annotations are added or removed and should be somewhat stable.

**Comment by naglepuff** [comment]
So a default convention could look something like `<style>_<type>_<number>`?

What would sensible counter behavior look like? If I have elements

- default_point_1
- default_point_2
- default_point_3

And I delete the second entry, should default_point_3 change itself to default_point_2? It it stays default_point_3 should it be like that forever (i.e. the next time I load the annotation)? If that's the case, should we change the upload annotation process to fill in a default value for each element's label?

**Comment by manthey** [comment]
I think it is perfectly fine to use spaces (e.g., I'd rather see "default point 1" than "default_point_1"). 

I'd rather not store the values into the labels -- that should be reserved for when the user has decided to have a label (plus it adds to the data volume).  I think that means that the elements end up getting renumbered.

I'm not sure about the element number, because it will be slow to have consistent behavior.  When we delete an element, we just remove the html without altering all the others (and, when we add an element, we just add it without modifying the other html).  This means that as long as the element list is not fully rerendered, we probably will have numbers that have apparent gaps (and new numbers will probably just be based on the last entry).  I think if the default counter was purely based on the initial element position (e.g., you would have "point 1", "polygon 2", "point 3" rather than "point 1", "polygon 1", "point 2"), and new elements just extend from where the last maximum was, this would look consistent (and be somewhat obvious when deleting similar entries), and when a rerender would reset the numbering, it wouldn't be bad.  But we'd have to try it to see if it actually makes sense.
