### ISSUE TITLE
Need ability to create fixed-size rectangular annotations

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsUI#26]
This is useful for creating things like regions of interest (ROI) where size may need to be fixed instead of being determined by mouse dragging.

**Comment by manthey** [comment]
This should be an option on rectangle and ellipse annotations.  One UI method of doing this would be to have a drop down arrow like the multipolygon ROI that would show a dialog to constrain aspect ratio or size.  The rectangle/ellipse tool would then change somehow to show it is constrained.
