### ISSUE TITLE
Please select a large image source

### ISSUE THREAD

**Issue by MartinKlefas** [DigitalSlideArchive/HistomicsUI#365]
I'm trying to use the slides in UnitoPatho as my test data set, these are all in PNG format, which I think is causing the issue where It's saying "please select a "large image" item." when I try to open them - I've run both lines from the guide:

`pip install large-image[sources] --find-links https://girder.github.io/large_image_wheels` 
&
`pip install large-image-source-tiff large-image-source-openslide --find-links https://girder.github.io/large_image_wheels`

Is there one specific to PNG files - I think openslide opens those too?

**Comment by MartinKlefas** [comment]
Thank you, I've added that package - where in the config files is max_small_image_size - I can't find it in any of the yaml files or anywhere in this repository or the main dsa one?

**Comment by manthey** [comment]
There is an example of adjusting the config here: https://girder.github.io/large_image/config_options.html#configuration-from-python

**Comment by MartinKlefas** [comment]
OK, sorry this may be a stupid question: I've installed those packages via pip, and changed the config file, then I've shut down dsa with `docker-compose down`, and rerun it with `docker-compose up` but it's still giving the same error message  "please select a "large image" item." 

Is there anything I need to enable to make sure that histomics knows I've installed the pil backend?

**Comment by MartinKlefas** [comment]
For other people reading this, of course it's the docker compose yamls that should be changed - there's even examples in the existing one of how to do it. RTFM before posting issues...
