### ISSUE TITLE
HistomicsUI brand name Actions label doesn't update

### ISSUE THREAD

**Issue by BryonLewis** [DigitalSlideArchive/HistomicsUI#51]
If the label for the HistomicsUI install is changed in the plugin settings.  The label in the actions doesn't update to the new value.
![image](https://user-images.githubusercontent.com/61746913/76109015-a6286b80-5fa9-11ea-9952-5ca216ed5209.png)
![image](https://user-images.githubusercontent.com/61746913/76109023-a9bbf280-5fa9-11ea-8f37-7755b40f7f93.png)
These two should match all times.

**Comment by manthey** [comment]
The link that "Open in HistomicsUI" should also be based on settings.  Specifically, this doesn't handle being in a proxy properly and also hard-codes the application webroot (incorrectly, too).

The proxy issue can be handled by using a relative path.  The correct webroot is in the `histomicsui.webroot_path` setting.  That is, the href should be `./${webroot}#?image=${this.model.id}".

**Comment by manthey** [comment]
Resolved in #54.
