### ISSUE TITLE
Editing polygon vertices

### ISSUE THREAD

**Issue by kheffah** [DigitalSlideArchive/HistomicsUI#69]
This is already part of GeoJS, just needs to be part of HistomicsUI>
Like: https://opengeoscience.github.io/geojs/examples/annotations/?

This is useful when making a really complex polygon. Editing is easier than re-drawing in a number of cases.

**Comment by ds2268** [comment]
@kheffah When should we expect this feature to be included?

**Comment by kheffah** [comment]
@ds2268 I have no idea unfortunately. @manthey is probably better positioned to give a response here.

**Comment by manthey** [comment]
This was added in #100 back in April.  After clicking on an annotation so its elements are listed in the lower right panel, right-click a polygon and select "Edit shape" (or hover over it and type E).
