### ISSUE TITLE
Display time when the last annotation data is saved into Database or display the status of annotation data saved

### ISSUE THREAD

**Issue by com1984** [DigitalSlideArchive/HistomicsUI#70]
I understand that annotation data is automatically saved to database when annotation is created on WSI. 
However, I have often feedbacks from annotators that their annotation data done previously is disappeared (or not saved). 

For this reason, it may be good to **display time when the last annotation data is saved into database**. (like a google doc)
So, users believe their annotation data keeps saving.

**Comment by manthey** [comment]
There was an issue that was fixed in https://github.com/DigitalSlideArchive/HistomicsTK/pull/761, including showing a spinner if annotations are still saving.
